trigger:
- main # Adjust to your branch

pool:
  name: ARM # Self-hosted agent pool name

stages:
- stage: RunOWASPZAPScan
  displayName: 'Run OWASP ZAP Scan'
  jobs:
  - job: Scan
    displayName: 'Perform OWASP ZAP Vulnerability Scan'
    steps:
    - script: |
        docker --version
        docker pull zaproxy/zap-stable
        # Run OWASP ZAP scan and capture the exit code
        docker run --rm -v $(System.DefaultWorkingDirectory):/zap/wrk/:rw -t zaproxy/zap-stable zap-full-scan.py -t $(targetUrl) -r /zap/wrk/$(htmlFileName) -x /zap/wrk/$(xmlFileName) || true
      displayName: 'Run OWASP ZAP Scan'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/$(htmlFileName)'
        artifactName: 'ZAPReportHTML'
      displayName: 'Publish OWASP ZAP HTML Report'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/$(xmlFileName)'
        artifactName: 'ZAPReportXML'
      displayName: 'Publish OWASP ZAP XML Report'
