trigger:
- main  # Or the branch you want to trigger on

pool:
  name: ARM  # Replace with your self-hosted agent pool name

stages:
- stage: CheckDocker
  jobs:
  - job: CheckDockerJob
    steps:
    - script: |
        docker --version
      displayName: 'Check Docker Installation'
