trigger:
- main  # Adjust this to your target branch

pool:
  name: ARM  # Your self-hosted agent pool name

stages:
- stage: VulnerabilityScan
  jobs:
  - job: ZAPScan
    displayName: "OWASP ZAP Vulnerability Scan"
    steps:
    - script: |
        docker --version
        docker pull zaproxy/zap2docker-stable  # Correct image name
      displayName: "Pull OWASP ZAP Docker Image"
      
    - script: |
        docker run --rm -v $(pwd):/zap/wrk/:rw -t zaproxy/zap2docker-stable zap-full-scan.py \
        -t http://your-target-url.com \
        -r zap_report.html \
        -x zap_report.xml
      displayName: "Run OWASP ZAP Scan"

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/zap_report.html'
        artifactName: 'ZAPReport'
      displayName: 'Publish OWASP ZAP Report'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/zap_report.xml'
        failTaskOnFailedTests: true
      displayName: 'Publish Test Results'

