# Docker Image Scanning

trigger:
- main # Adjust the branch as needed

pool:
  name: ARM
  vmImage: 'ubuntu-latest' # Changed to a more common image

stages:
- stage: OWASP_ZAP_Scan
  displayName: OWASP ZAP Security Scan
  jobs:
  - job: OWASP_ZAP_Scan_Job
    displayName: OWASP ZAP Scan Job
    pool:
      name: ARM
      demands:
      - agent.name -equals arm
    steps:

    - task: Docker@2
      inputs:
        command: 'run'
        container: 'owasp/zap2docker-stable'
        arguments: |
          zap-full-scan.py -t http://your-target-url.com -r zap_report.html -x zap_report.xml
      displayName: 'Run OWASP ZAP Scan'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/zap_report.html'
        artifactName: 'ZAPReport'
      displayName: 'Publish OWASP ZAP Report'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/zap_report.xml'
        failTaskOnFailedTests: true
      displayName: 'Publish Test Results'

- stage: Review_Report
  displayName: Review ZAP Report
  dependsOn: OWASP_ZAP_Scan
  jobs:
  - job: Review_Report_Job
    displayName: Review Report Job
    pool:
      name: ARM
      demands:
      - agent.name -equals arm
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        artifactName: 'ZAPReport'
        downloadPath: '$(System.DefaultWorkingDirectory)'
      displayName: 'Download ZAP Report'

    - script: |
        # Review or take further actions on the ZAP report if needed
        echo "OWASP ZAP Report downloaded"
      displayName: 'Review ZAP Report'
