trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  zapPath: '/usr/share/zaproxy'
  targetUrl: 'https://your-target-url.com'
  reportDir: '$(Build.ArtifactStagingDirectory)/owasp-reports'
  reportHtml: 'owasp-zap-report.html'
  reportXml: 'owasp-zap-report.xml'

jobs:
- job: OWASP_ZAP_Scan
  displayName: 'Run OWASP ZAP Security Scan'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        sudo apt-get update
        sudo apt-get install zaproxy -y
      displayName: 'Install OWASP ZAP'

    - script: |
        zap.sh -daemon -port 8080 -config api.addrs.addr.name=127.0.0.1 -config api.addrs.addr.regex=false
        sleep 30  # Give ZAP time to start
      displayName: 'Start OWASP ZAP in daemon mode'

    - script: |
        zap.sh -cmd -quickurl $(targetUrl) -quickout $(reportDir)/$(reportXml)
      displayName: 'Run OWASP ZAP Scan'

    - script: |
        zap.sh -cmd -quickurl $(targetUrl) -quickout $(reportDir)/$(reportHtml)
      displayName: 'Generate OWASP ZAP HTML Report'

    - publish: $(reportDir)
      artifact: 'OWASPReports'
      displayName: 'Publish OWASP ZAP Reports'
