# OWASP Scanning Pipeline Without Daemon

trigger:
- main # Adjust the branch as needed

pool:
  name: ARM # Replace with your self-hosted agent pool name

stages:
- stage: RunOWASPZAPScan
  displayName: 'Run OWASP ZAP Scan'
  jobs:
  - job: Scan
    displayName: 'Perform OWASP ZAP Vulnerability Scan'
    steps:
    - script: |
        # Display Docker version
        docker --version
        # Pull the latest OWASP ZAP Docker image
        docker pull zaproxy/zap-stable
      displayName: 'Prepare Docker Image'

    - script: |
        # Run OWASP ZAP scan and generate XML report
        docker run --rm -v $(System.DefaultWorkingDirectory):/zap/wrk/:rw -t zaproxy/zap-stable zap-full-scan.py -t http://cricbuzz.com -x abc.xml
      displayName: 'Run OWASP ZAP Scan'
    
    - script: |
        # Generate HTML report from the XML report
        docker run --rm -v $(System.DefaultWorkingDirectory):/zap/wrk/:rw -t zaproxy/zap-stable zap-cli report -f html -o /zap/wrk/abc.html
      displayName: 'Generate HTML Report'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/abc.html'
        artifactName: 'ZAPReport'
      displayName: 'Publish OWASP ZAP Report'
